# You can add custom configs in the myConfig.sh, but Please DO NOT edit this file!

### myConfig.sh template:
# source $Qfig_loc/command/xxx # add functions defined in xxx to bash
# unsetFunctionsInFile $Qfig_loc/command/xxx # unset functions defined in xxx from context

## The location of Qfig project
Qfig_loc=$(dirname "$0")

## Base configs
source $Qfig_loc/command/baseCommands.sh

## Custom configs
[ -f "$Qfig_loc/myConfig.sh" ] && source $Qfig_loc/myConfig.sh

## For complex functions only works for your current orgnization, add them to the tempCommands.sh
## All functions in this file will not be included in git
[ -f "$Qfig_loc/command/tempCommands.sh" ] && source $Qfig_loc/command/tempCommands.sh 
