# You can add custom configs in the myConfig.ps1, but Please DO NOT edit this file!

### myConfig.ps1 template:
# . $Qfig_loc/command/xxx # add functions defined in xxx to bash
# unsetFunctionsInFile $Qfig_loc/command/xxx # unset functions defined in xxx from context

## The location of Qfig project
$Qfig_loc = $PSScriptRoot

## Base configs
. $Qfig_loc\command\baseCommands.ps1

## Custom configs
. $Qfig_loc\myConfig.ps1

## For complex functions only works for your current orgnization, add them to the tempCommands.ps1
## All functions in this file will not be included in git
If (Test-Path $Qfig_loc\command\tempCommands.ps1) {
	. $Qfig_loc\command\tempCommands.ps1
}
