# You can add custom configs in the myConfig.sh, but Please DO NOT edit this file!

### myConfig.sh template:
# source $Qfig_loc/command/xxx # add functions defined in xxx to bash
# unsetFunctionsInFile $Qfig_loc/command/xxx # unset functions defined in xxx from context

## The location of Qfig project
Qfig_loc=$(dirname "$0")

## The functions used in this script
function doNothing() {}

## Base configs
source $Qfig_loc/command/baseCommands.sh

## Custom configs
[ -f "$Qfig_loc/myConfig.sh" ] && source $Qfig_loc/myConfig.sh || doNothing


## For functions only works on current computer, add them to the tempCommands.sh/tempCommands.ps1
## All functions in these files will not be included in git
[ -f "$Qfig_loc/command/tempCommands.sh" ] && source $Qfig_loc/command/tempCommands.sh || doNothing 
[ -f "$Qfig_loc/command/tempCommands.ps1" ] && source $Qfig_loc/command/tempCommands.ps1|| doNothing 

unset -f doNothing
